### PR TITLE
FE PJ Spec game disp

### PR DESCRIPTION
**Pull request by Shadowda**
Created spectator_game.html template. Shows the game's name, players, and their roles. Loads messages with info regarding modification, deletion, or unmodified.

### CODE REVIEW

**Review by Voitheia — COMMENTED** [review]
I think that edited messages can still be deleted, so just copy over the modified section from line 59 into the deleted message section. Otherwise the code looks good to go.

**Comment by Shadowda** [comment]
> I think that edited messages can still be deleted, so just copy over the modified section from line 59 into the deleted message section. Otherwise the code looks good to go.

I'm not sure I understand. If an adversary modifies a message then deletes it, I asume the recipient player never sees the edited message. Does the spectator need to know? 

I was under the impression all deleted messages get the edited tag, whether the adversary actually changed the message or not.

**Comment by Voitheia** [comment]
removing pycache

**Comment by Voitheia** [comment]
whoops wrong one

**Comment by Shadowda** [comment]
New commits, template should world for cases for original messages by adversaries, and if the adversary does not change the sender/receiver. 

Case of edited then deleted comment will not show edited message, only the original.  

Case of original message by adversaries that is then been edited, has not been tested.

**Review by Voitheia — APPROVED** [review]
Looks good to go

**Pull request merged**
